baseURL = "https://parox.dev/"
languageCode = "en-us"
title = "Paro"
theme = "papermod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-HS9V0SKE1J"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Paro"
description = "Luca Parolini's landpage"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Me"
# images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "/static/favicon.ico"
favicon16x16 = "/static/favicon-16x16.png"
favicon32x32 = "/static/favicon-32x32.png"
apple_touch_icon = "/static/apple-touch-icon.png"
# safari_pinned_tab = "<link / abs url>"

[params.label]
text = "Home"
# icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = true
title = "Luca Parolini"
subtitle = "📜 Computer Engineer | 📚 MSc Cybersecurity student at Aalborg University, Copenaghen 🇩🇰"
imageUrl = ""
imageWidth = 120
imageHeight = 120
imageTitle = "That's me :)"

# [[params.profileMode.buttons]]
# name = "Posts"
# url = "posts"
#
# [[params.profileMode.buttons]]
# name = "Tags"
# url = "tags"
#
# [params.homeInfoParams]
# Title = "Hi there 👋"
# Content = "Welcome to my blog"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/luca-parolini-40b98a202/"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/cooparo"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/l_paro"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/paro_t"

[[params.socialIcons]]
name = "Email"
url = "mailto: work.tartly799@aleeas.com"

# [params.analytics.google]
# SiteVerificationTag = "XYZabc"
#
# [params.analytics.bing]
# SiteVerificationTag = "XYZabc"
#
# [params.analytics.yandex]
# SiteVerificationTag = "XYZabc"

# [params.cover]
# hidden = true
# hiddenInList = true
# hiddenInSingle = true
#
# [params.editPost]
# URL = "https://github.com/cooparo/parox/content"
# Text = "Suggest Changes"
# appendFilePath = true
#
# [params.fuseOpts]
# isCaseSensitive = false
# shouldSort = true
# location = 0
# distance = 1_000
# threshold = 0.4
# minMatchCharLength = 0
# limit = 10
# keys = [ "title", "permalink", "summary", "content" ]

# [[menu.main]]
# identifier = "categories"
# name = "categories"
# url = "/categories/"
# weight = 10
#
# [[menu.main]]
# identifier = "tags"
# name = "tags"
# url = "/tags/"
# weight = 20

# [markup.highlight]
# noClasses = false
